server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loggerdb

logging:
  level:
    root: INFO
    one:
      microproject:
        authx: INFO
