server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /authx

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loggerdb

authx:
  app-id: authx-001
  base-url-mapping:
    internal-url: http://localhost:8080/authx
    external-url: http://localhost:8080/authx
  global-admins:
    project-name: global-admins
    admin-user:
      username: admin-user
      password: s3cr3t
    admin-client:
      client-id: admin-client
      client-secret: secret

management:
  server:
    port: 7777
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    one:
      microproject:
        authx: INFO
