server:
  port: ${SERVER_PORT}

spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DB}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

authx:
  app-id: ${AUTHX_APP_ID}
  global-admins:
    project-name: global-admins
    admin-user:
      username: admin-user
      password: ${ADMIN_USER_PASSWORD}
    admin-client:
      client-id: admin-client
      client-secret: ${ADMIN_CLIENT_SECRET}

management:
  port: ${MANAGEMENT_PORT}
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    one:
      microproject:
        authx: INFO
