version: '3.6'

services:

  nginx-proxy:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - /opt/elastic/nginx-default.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - "elastic"
      - "kibana"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network-proxy==true
