version: '3.6'

services:

  mongodb:
    image: mongo:5.0.5-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3t
    volumes:
      - mongodb-data:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.persistence==true

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.persistence==true

volumes:
  mongodb-data:

networks:
  default:
    external: true
    name: authx-network