version: '3.3'

services:

  mongodb:
    image: mongo:5.0.3-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3t
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379

volumes:
  mongodb-data:
