# This workflow will build a Java project with Gradle
name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Docker version
        run: docker --version
      - name: Docker Compose version
        run: docker-compose --version
      - name: Run full test suite
        run: gradle clean build test
